

version: 2.1
jobs:
  build:
    docker:
      - image: rastasheep/ubuntu-sshd
    steps:
      - add_ssh_keys:
          fingerprints:
            - "a7:7f:41:3f:31:36:e0:25:ea:f1:7b:93:ed:ac:38:7b"
      - checkout
      - run:
          name: Updating code
          command: |
            ssh -o StrictHostKeyChecking=no ppsree@ppsree.net 'cd blog && git pull'
      - run:
          name: Restarting containers
          command: |
            ssh -o StrictHostKeyChecking=no ppsree@ppsree.net 'cd blog && make restart'